name: Brute force

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  brute-force:
    name: Brute force
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Run update script
        run: npm start
